create database partyplanner;

use partyplanner;

create table cocktail (
    idDrink int not null,
    strDrink varchar(30),
    strInstructions varchar(1000),
    strIngredient1 varchar(30),
    strIngredient2 varchar(30),
    strIngredient3 varchar(30),
    strIngredient4 varchar(30),
    strIngredient5 varchar(30),
    strIngredient6 varchar(30),
    strIngredient7 varchar(30),
    strIngredient8 varchar(30),
    strIngredient9 varchar(30),
    strIngredient10 varchar(30),
    strIngredient11 varchar(30),
    strIngredient12 varchar(30),
    strIngredient13 varchar(30),
    strIngredient14 varchar(30),
    strIngredient15 varchar(30),
    strMeasure1 varchar(30),
    strMeasure2 varchar(30),
    strMeasure3 varchar(30),
    strMeasure4 varchar(30),
    strMeasure5 varchar(30),
    strMeasure6 varchar(30),
    strMeasure7 varchar(30),
    strMeasure8 varchar(30),
    strMeasure9 varchar(30),
    strMeasure10 varchar(30),
    strMeasure11 varchar(30),
    strMeasure12 varchar(30),
    strMeasure13 varchar(30),
    strMeasure14 varchar(30),
    strMeasure15 varchar(30),
    strDrinkThumb varchar(100),
    primary key(idDrink)
);

create table meal (
    idMeal int not null,
    strMeal varchar(50),
    strArea varchar(30),
    strInstructions varchar(1000),
    strIngredient1 varchar(30),
    strIngredient2 varchar(30),
    strIngredient3 varchar(30),
    strIngredient4 varchar(30),
    strIngredient5 varchar(30),
    strIngredient6 varchar(30),
    strIngredient7 varchar(30),
    strIngredient8 varchar(30),
    strIngredient9 varchar(30),
    strIngredient10 varchar(30),
    strIngredient11 varchar(30),
    strIngredient12 varchar(30),
    strIngredient13 varchar(30),
    strIngredient14 varchar(30),
    strIngredient15 varchar(30),
    strIngredient16 varchar(30),
    strIngredient17 varchar(30),
    strIngredient18 varchar(30),
    strIngredient19 varchar(30),
    strIngredient20 varchar(30),
    strMeasure1 varchar(30),
    strMeasure2 varchar(30),
    strMeasure3 varchar(30),
    strMeasure4 varchar(30),
    strMeasure5 varchar(30),
    strMeasure6 varchar(30),
    strMeasure7 varchar(30),
    strMeasure8 varchar(30),
    strMeasure9 varchar(30),
    strMeasure10 varchar(30),
    strMeasure11 varchar(30),
    strMeasure12 varchar(30),
    strMeasure13 varchar(30),
    strMeasure14 varchar(30),
    strMeasure15 varchar(30),
    strMeasure16 varchar(30),
    strMeasure17 varchar(30),
    strMeasure18 varchar(30),
    strMeasure19 varchar(30),
    strMeasure20 varchar(30),
    strMealThumb varchar(100),
    primary key(idMeal)
);

create table user (
    idUser int not null auto_increment,
    firstName varchar(30),
    lastName varchar(30),
    phoneNumber varchar(20),
    primary key(idUser)   
);

create table event (
    idEvent int not null auto_increment,
    idUser int,
    date DateTime,
    city varchar(85),
    state varchar(2),
    primary key(idEvent),
    foreign key eventUser(idUser) references user(idUser)
);
